env: 
app:
  name: nginx
  volume: start-page
  replicas:
  resources:
    requests:
      memory: "250Mi"
      cpu: "500m"
    limits:
      memory: "500Mi"
      cpu: "1000m"
  port: 9090
securityContext:
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001