apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.env }}-test
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels: 
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      securityContext:
      {{- with .Values.securityContext }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image }}:{{ $.Chart.Version }}"
          ports:
          - containerPort: {{ .Values.app.port }}
          volumeMounts:
          - mountPath: /app/index.html
            name: {{ .Values.app.volume }}
            subPath: index.html
          resources:
            {{- with .Values.app.resources }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
      imagePullSecrets:
        - name: docker-github
      volumes:
        - name: {{ .Values.app.volume }}
          configMap:
            name: {{ .Values.app.name }}-config
