apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-svc
  namespace: {{ .Values.env }}-test
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.app.port }}
    targetPort: {{ .Values.app.port }}
  selector:
    app: {{ .Values.app.name }}